---
name: ZMK Full Firmware Build

permissions:
  contents: read
  issues: read
  actions: read
  pull-requests: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - "full/**"
      - "boards/**"
      - "zephyr/**"
      - "build.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "full/**"
      - "boards/**"
      - "zephyr/**"
      - "build.yaml"
  workflow_dispatch:
    # No specific configuration required

jobs:
  build:
    name: Full Firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: full
      archive_name: full
